name: latest_movies
description: A new Flutter project.

publish_to: "none"

version: 1.2.53+70

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  hooks_riverpod: 
  flutter_hooks: ^0.18.4
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  shared_preferences: ^2.0.15
  flutter_vlc_player: ^7.4.0
  focus_notifier:
    git:
      url: https://github.com/iamsahilsonawane/focus_notifier.git
      ref: main
  firebase_crashlytics: ^4.1.0
  audio_video_progress_bar: ^0.10.0
  dio: ^4.0.6
  json_annotation: ^4.6.0
  equatable: ^2.0.4
  flutter_staggered_grid_view: ^0.6.2
  intl: ^0.18.1
  url_launcher: ^6.1.5
  ota_update: ^4.0.1
  firebase_remote_config: ^5.1.0
  firebase_analytics: ^11.3.0
  package_info_plus: 
  # chewie: ^1.3.3
  video_player: ^2.9.1
  scrollable_positioned_list: ^0.3.5
  android_intent_plus: ^3.1.5
  pin_code_fields: ^7.4.0
  uuid: ^4.0.0
  youtube_player_flutter: ^8.1.2
  shimmer: ^3.0.0
  flutter_blurhash: ^0.8.2
  octo_image: ^2.0.0
  device_info_plus: 
  android_id: ^0.4.0
  flutter_native_splash: 
  ensure_visible_when_focused: ^1.2.0
  localizely_sdk: ^2.5.7

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - shorebird.yaml

flutter_intl:
  localizely:
    ota_enabled: true # Required for Over-the-Air translation updates
