name: latest_movies
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  hooks_riverpod: ^1.0.4
  flutter_hooks: ^0.18.4
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  shared_preferences: ^2.0.15
  flutter_vlc_player: ^7.1.5
  focus_notifier:
    git:
      url: https://github.com/iamsahilsonawane/focus_notifier.git
      ref: main 
  # chewie: ^1.3.3
  # video_player: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
